apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana-local"
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm-local.observability.svc.cluster.local:8429
    isDefault: true
    jsonData:
      timeInterval: "20s"
