apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: finops-platform
  source:
    repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
    targetRevision: HEAD
    path: platform/governance/kyverno/policies/local
  destination:
    server: https://kubernetes.default.svc
    namespace: governance-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
