apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project-platform.yaml
  - application-kyverno.yaml
  - application-governance-policies.yaml
  - application-observability.yaml
  - application-platform.yaml
  - application-workloads.yaml
