projects:
  - name: finops-platform
    namespace: argocd
    description: GitOps project for kubernetes-finops-platform resources
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

applications:
  - name: infra-bootstrap
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "-1"
    project: finops-platform
    source:
      repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      path: gitops/02-infra/charts/infra-bootstrap
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: kyverno
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "0"
    project: finops-platform
    sources:
      - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
        targetRevision: HEAD
        ref: values
      - repoURL: https://kyverno.github.io/kyverno/
        chart: kyverno
        targetRevision: 3.5.3
        helm:
          valueFiles:
            - $values/gitops/02-infra/values/kyverno.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: governance-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

  - name: kyverno-policies
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "1"
    project: finops-platform
    source:
      repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      path: gitops/02-infra/charts/kyverno-policies
    destination:
      server: https://kubernetes.default.svc
      namespace: governance-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: observability
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "2"
    project: finops-platform
    sources:
      - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
        targetRevision: HEAD
        path: gitops/02-infra/charts/observability-objects
      - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
        targetRevision: HEAD
        ref: values
      - repoURL: https://victoriametrics.github.io/helm-charts/
        chart: victoria-metrics-k8s-stack
        targetRevision: 0.91.2
        helm:
          releaseName: vm-local
          valueFiles:
            - $values/gitops/02-infra/values/victoria-metrics.yaml
      - repoURL: https://victoriametrics.github.io/helm-charts/
        chart: victoria-logs-single
        targetRevision: 0.3.3
        helm:
          releaseName: vl-local
          valueFiles:
            - $values/gitops/02-infra/values/victoria-logs.yaml
      - repoURL: https://grafana.github.io/helm-charts
        chart: tempo
        targetRevision: 1.24.4
        helm:
          releaseName: tempo-local
          valueFiles:
            - $values/gitops/02-infra/values/tempo.yaml
      - repoURL: https://grafana.github.io/helm-charts
        chart: grafana-operator
        targetRevision: 5.24.0
        helm:
          releaseName: grafana-operator
          valueFiles:
            - $values/gitops/02-infra/values/grafana-operator.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: observability
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

  - name: finops
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "3"
    project: finops-platform
    sources:
      - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
        targetRevision: HEAD
        path: gitops/03-finops/charts/finops-objects
      - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
        targetRevision: HEAD
        ref: values
      - repoURL: https://opencost.github.io/opencost-helm-chart
        chart: opencost
        targetRevision: 2.5.29
        helm:
          releaseName: opencost
          valueFiles:
            - $values/gitops/03-finops/values/opencost.yaml
      - repoURL: https://charts.fairwinds.com/stable
        chart: goldilocks
        targetRevision: 11.0.0
        helm:
          releaseName: goldilocks
          valueFiles:
            - $values/gitops/03-finops/values/goldilocks.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: finops-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

  - name: business-app
    namespace: argocd
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "4"
    project: finops-platform
    source:
      repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      path: gitops/04-business-app/charts/sample-workloads
      helm:
        valueFiles:
          - ../../values/workloads.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
