apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: finops-platform
  source:
    repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
    targetRevision: HEAD
    path: gitops/02-infra/event-exporter/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: governance-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
