apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: finops-platform
  sources:
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: ztunnel
      targetRevision: 1.30.4
      helm:
        releaseName: ztunnel
        valueFiles:
          - $values/gitops/02-infra/ztunnel/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
