apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: finops-platform
  sources:
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      path: gitops/03-finops/opencost/manifests
      directory:
        recurse: true
    - repoURL: https://opencost.github.io/opencost-helm-chart
      chart: opencost
      targetRevision: 2.5.29
      helm:
        releaseName: opencost
        valueFiles:
          - $values/gitops/03-finops/opencost/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
