apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: finops-platform
  sources:
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      path: gitops/02-infra/observability-objects/victoria-stack/rules
      directory:
        recurse: true
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.91.2
      helm:
        releaseName: vm-local
        valueFiles:
          - $values/gitops/02-infra/observability-objects/victoria-stack/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
