apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messenger-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: finops-platform
  source:
    repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
    targetRevision: HEAD
    path: gitops/04-messenger/messenger-redis/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: messenger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
