apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vmalert
  namespace: observability
  labels:
    app.kubernetes.io/name: vmalert
spec:
  hostnames:
    - vmalert.finops.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: edge
      namespace: edge
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: vmalert-vm-local-victoria-metrics-k8s-stack
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
