{{- range .Values.workloads }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
{{ toYaml .labels | indent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
{{ toYaml .labels | indent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .containerPort }}"
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          args:
            - -text={{ .text }}
            - -listen=:{{ .containerPort }}
          ports:
            - name: http
              containerPort: {{ .containerPort }}
          resources:
{{ toYaml .resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
{{ toYaml .labels | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
    - name: http
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
---
{{- end }}
