apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  labels:
    dashboards: {{ .Values.grafana.instanceLabel | quote }}
spec:
  config:
    security:
      admin_user: {{ .Values.grafana.adminUser | quote }}
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_INSTALL_PLUGINS
                  value: {{ .Values.grafana.installPlugins | default "victoriametrics-logs-datasource" | quote }}
