apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoriametrics/local
  - victorialogs/local
  - tempo/local
  - grafana/local
  - grafana/dashboards/application-overview/dashboard-configmap.yaml
  - grafana/dashboards/kubernetes-capacity/dashboard-configmap.yaml
  - grafana/dashboards/finops/dashboard-configmap.yaml
