apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-finops-platform-root
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/vigregus/kubernetes-finops-platform.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-apps
      targetRevision: 1.4.1
      helm:
        valueFiles:
          - $values/gitops/02-infra/argocd-apps/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
